### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/infografia-AlynGomez12#1]
[ALYN XIMEMA GOMEZ HERNANDEZ INFOGRAFIA.pdf](https://github.com/user-attachments/files/16754395/ALYN.XIMEMA.GOMEZ.HERNANDEZ.INFOGRAFIA.pdf)

**Comment by LenninGS-0** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:14/14
Referencias:14/14
Presentación:14/14
Calificación Final: 19.8/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
